language: python

sudo: required
dist: trusty

python:
  - "2.7"

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get -qq update
  - sudo apt-get install python-dev libgdal1-dev gdal-bin

install:
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - pip install -r dev-requirements.txt
  - pip install -e .
  - git clone -b 2.4.x https://github.com/GeoNode/geonode.git
  - cp local_settings.py.template geonode/geonode/local_settings.py
  - pip install -e geonode

script:
  - flake8 --config flake8.cfg dataqs
  - pushd geonode
  - python manage.py test dataqs
  - popd
