###
# Install GeoServer from Custom GeoNode Build
#
---

- name: ensure apt cache is up to date
  apt:
    update_cache: true
  become: true

- name: install Tomcat
  apt:
    name: ['tomcat8', 'unzip']
  become: true

- name: copy the Tomcat setenv.sh file to /usr/share/tomcat7/bin
  template:
    src: setenv.sh
    dest: /usr/share/tomcat8/bin/setenv.sh
  become: true

- name: copy the tomcat8 file to /etc/default
  template:
    src: tomcat8
    dest: /etc/default/tomcat8
  become: true

- name: Create Geoserver data directory
  file:
    path: /data/
    state: directory
  become: true

- name: Download Geoserver (remote)
  become: true
  get_url:
    dest: /tmp/geoserver.war
    url: "{{ geoserver_url }}"
    owner: 0
    group: 0
    mode: 0644
    validate_certs: no

- name: Unzip Geoserver WAR file
  command: unzip -o -d '/tmp/geoserver' '/tmp/geoserver.war'
  become: true

- name: Copy Geoserver web.xml file with custom data directory
  template:
    src: web.xml
    dest: /tmp/geoserver/WEB-INF/web.xml
  become: true

- name: Move data files
  command: mv -n '/tmp/geoserver/data' '/data/geodata'
  become: true

- name: Move web app
  command: mv -n '/tmp/geoserver' '/var/lib/tomcat8/webapps/geoserver'
  become: true

- name: reset geoserver owner
  file:
    state: directory
    owner: tomcat8
    group: "{{ deploy_user }}"
    path: "/data"
    mode: 0774
    recurse: true
  become: true

- name: Restart Tomcat
  service:
    name: tomcat8
    state: restarted
  become: true
