###
# Install PostGIS and Postgres 9.5 from the main apt repo.
#
---

- name: install python-psycopg2
  apt:
    name: python3-psycopg2
  become: true

- name: install PostGIS
  apt:
    name: postgresql-9.5-postgis-2.2
  become: true

- name: stop postgres service
  service:
    name: postgresql
    state: stopped
  become: true

- name: setup postgres cluster to default to utf8
  shell: "pg_dropcluster 9.5 main ; pg_createcluster -e UTF-8 9.5 main"
  become: true

- name: start postgres service
  service:
    name: postgresql
    state: started
  become: true


- name: update postgres client configuration
  template:
    src: pg_hba.conf
    dest: /etc/postgresql/9.5/main/pg_hba.conf
  become: true
  notify:
    - restart postgres_postgis

- name: restart postgres_post_configuration
  command: /etc/init.d/postgresql restart
  become: true

- name: create database user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: LOGIN,CREATEDB,NOSUPERUSER
  # in case the user already exists
  ignore_errors: True
  notify:
    - restart postgres_postgis
