###
# Installs nginx
#
---

- name: ensure apt cache is up to date
  apt:
    update_cache: true
  become: true

- name: ensure nginx is installed
  apt:
    name: nginx-extras
  become: true

- name: write nginx configuration for multiple subdomains
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  become: true
  notify:
    - restart nginx
