###
# Install uwsgi from pypi and configure it with upstart in emperor mode.
#
---

- name: ensure web server packages are installed
  apt:
    name: ["python3-dev", "python3-pip", "uwsgi"]
  become: true

- name: create /etc/uwsgi to place apps
  file:
    path: /etc/uwsgi
    owner: www-data
    group: www-data
    state: directory
    mode: 0755
  become: true

- name: write default vassals configuration file
  template:
    src: vassals-default.skel.j2
    dest: /etc/uwsgi/vassals-default.skel
  become: true

- name: write uwsgi configuration for upstart in emperor mode
  template:
    src: emperor.uwsgi.service
    dest: /etc/systemd/system/emperor.uwsgi.service
  become: true
  notify:
    - restart uwsgi
